화면 레이아웃
youngH02/sohochat pull request #2
Opened 2023-12-03 23:16 UTC by youngH02

1. 화면 전체 레이아웃
2. 이미지 추가 및 상단 고정
Q. position: fixed 로 상단 타이틀, 상자 고정했더니 app 컴포넌트 하위로 들어가지 않습니다(각각 다시 설정해야함)
Q. 스크롤이 고정된 영역 포함 전체로 생기는데, 아래쪽 질문영역에만 생기게도 할 수 있을까요?

2023-12-04 13:20 UTC, nukeguys requested changes
Q. position: fixed 로 상단 타이틀, 상자 고정했더니 app 컴포넌트 하위로 들어가지 않습니다(각각 다시 설정해야함)
=> 이건 제가 이해를 못해서 구두로 질문드릴게요.
Q. 스크롤이 고정된 영역 포함 전체로 생기는데, 아래쪽 질문영역에만 생기게도 할 수 있을까요?
=> 네, 아래 스크롤이 필요한 영역에 높이를 지정하고 overflow 속성을 주면 가능해요.

이 내용들하고 리뷰 남긴 것들하고 내일 같이 한 번 보시죠~

2023-12-04 13:20 UTC, nukeguys commented on src/App.css
> +  height: 800px;
.App에 있는 text-align하고 height를 지정한 이유가 있을까요? 개인적으로는 아래 이유들로 없어도 되지 않을까 싶어요.
- text-align은 하위 전체적으로 적용이 될 거라 왼쪽정렬이 주로 사용되는걸 감안하면 사용하는 곳에서 각각 왼쪽 정렬을 해주는 것보다 가운데 정렬을 필요한 곳에 설정해주는게 좀 더 효율적일 것 같아요.
- height는 화면 전체를 차지하도록 해주는게 좋을 것 같아서 굳이 높이 지정은 하지 않는게 좋을 것 같아요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/Header.module.css
> +  min-width: 360px;
부모(App)에 min-width가 적용되어 있고 여기서는 width 100%라서 min-width는 별도로 지정해주지 않아도 될 것 같아요.
의미상 "타이틀은 가로로 꽉 채운다"라고 보면 없는게 좀 더 자연스럽기도 하구요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/Header.module.css
> +  color: var(--gray900, #2e2e30);
css variable(--gray900)이 정의가 되어 있지 않네요.
fallback값으로 적용되긴 하는데, 정의를 해주거나 아니면 그냥 `#2e2e30`를 직접 써주는게 좋을 것 같아요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/QuestionGuide.jsx
> +  const nowQ = useRef();
이름을 좀 더 직관적으로 작성해주면 좋을 것 같아요.
네이밍에 정답은 없지만 `questionInput` 정도는 어떨까요?

그런데 이미 입력값을 input에 저장하고 있으니 onClick에서는 input을 사용하면 nowQ는 없어도 될 것 같아요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/QuestionGuide.jsx
> +  const onChange = (e) => {
네이밍은 규칙을 정하기 나름이지만,
실제 이벤트를 처리하는 함수들은 `on` 대신 `handle` prefix를 붙여주면 가독성이 좀 더 좋을 것 같아요.
(on은 prop의 의미로 handle은 실제 처리하는 함수를 나타내는 prfix로)
`onChange` => `handleChange`, `onClick` => `handleClick`

2023-12-04 13:20 UTC, nukeguys commented on src/components/QuestionGuide.module.css
> +.question_guide {
왠지 피그마에 나오는 css들을 그대로 넣지 않았나 싶긴한데, 불필요한 것들이 많을 거라 필요한 것들만 사용하고 나머지는 제거 해주는게 좋을 것 같아요. 지금은 css에 익숙하지 않으니 일단 이 부분은 참고만 하고 스킵~ 하겠습니다.

2023-12-04 13:20 UTC, nukeguys commented on src/App.js
> +const questionsSet = [
이 데이터는 초기값을 의미하니까 그 의미를 담아서 INITIAL_QUESTION_SET 등으로 해주면 어떨까요?
그리고 실제로 아래에서 질문/응답 데이터를 의미하는 state를 questionSet으로 해주면 좀 더 명확할 것 같아요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/Chat.module.css
> +.qalist {
컴포넌트는 QAList인데 스타일은 Chat이라 이름을 동일하게 맞춰주면 좋을 것 같아요.

2023-12-04 13:20 UTC, nukeguys commented on src/components/QAList.jsx
> +import React, { useEffect } from "react";
useEffect 는 사용하지 않는다고 eslint에서 잡히네요.
필요 없는 import는 지워주면 좋을 것 같아요.

2023-12-05 06:26 UTC, youngH02 commented on src/components/Header.module.css
> +  min-width: 360px;
position: fixed; 를 사용하면서, app.css에서 설정한 min-width 가 적용되지 않아요

2023-12-05 08:57 UTC, nukeguys approved these changes
LGTM 👍🏻

2023-12-05 08:57 UTC, merged