Feature/chatapi
youngH02/sohochat pull request #3
Opened 2023-12-05 06:29 UTC by youngH02

레이아웃 - 리뷰 사항 반영
chat api 작성중..
 - api에서 응답 안옴 pending
 - 응답 오더라도 화면에서 못기다리고 있음...

2023-12-06 04:48 UTC, nukeguys commented
@youngH02  conflict이 생겼네요. 요거 확인하셔서 수정 한 번 해주세요~

2023-12-15 04:30 UTC, nukeguys requested changes
정리만 되면 어느정도 깔끔하게 마무리가 될 것 같은데, 이후에 상태관리 라이브러리 적용까지 같이 한 번 해보시면 어떨까요?
리덕스는 어려울 수 있으니까 zustand? 정도로 적용해보면 좋을 것 같아요.
참고) https://github.com/pmndrs/zustand

2023-12-15 04:30 UTC, nukeguys commented on src/components/QuestionGuide.jsx
> +//import streamTest from "./StreamTest";
사용안하는 코드는 지워주시면 좋을 것 같습니다.

2023-12-15 04:30 UTC, nukeguys commented on src/components/QuestionGuide.jsx
> +    console.log("requestChat");
지금은 연습 프로젝트라 상관없지만, 가급적 테스트 후에 console.log도 지워주는게 좋습니다. (필요에 따라 console.error 등은 쓰기도 하지만)

2023-12-15 04:30 UTC, nukeguys commented on src/components/useAsync.js
> +import { useReducer, useEffect } from "react";
이 파일은 사용하지 않는 것 같아서, 지우면 좋을 것 같아요.

2023-12-15 04:30 UTC, nukeguys commented on src/App.js
> +    case "ADD_ANSWER":
typescript면 그나마 괜찮을 수 있지만 지금은 js이기 때문에,
여러 곳에서 같이 사용해야 하는 action type같은 경우는 상수로 따로 선언하고 분리해서 사용하도록 해주면 좋을 것 같아요.

2023-12-15 04:30 UTC, nukeguys commented on src/components/StreamTest.jsx
> +function readAllChunks(readableStream) {
이 파일도 사용하지 않으면 지워주시면 좋을 듯 해요.

2023-12-15 04:33 UTC, nukeguys commented
![image](https://github.com/youngH02/sohochat/assets/3296225/0dc826de-4330-495a-a075-b21277a120bc)
인풋이 가로로 꽉차게 되어 있는데 실제 입력되는 영역은 제한되어 있네요. 이것도 수정되면 좋을 것 같아요.

2023-12-18 05:14 UTC, youngH02 commented on src/App.js
> +    case "ADD_ANSWER":
const ACTION = { ADD_QA: "ADD_QA", ADD_ANSWER: "ADD_ANSER" };

2023-12-21 08:27 UTC, nukeguys approved these changes
LGTM 👍🏻

2023-12-21 08:30 UTC, merged